<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6AFPICQ" failures="0" tests="1" name="framework.test.FreeEnrollment_UK_PartyLite" time="570.895" errors="1" timestamp="2021-07-23T21:31:14 IST" skipped="0">
  <testcase classname="framework.test.FreeEnrollment_UK_PartyLite" name="createGuestOrder" time="570.895">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at framework.utils.Reports.reportStep(Reports.java:72)
at framework.utils.Reports.reportStep(Reports.java:82)
at framework.test.FreeEnrollment_UK_PartyLite.createGuestOrder(FreeEnrollment_UK_PartyLite.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- createGuestOrder -->
</testsuite> <!-- framework.test.FreeEnrollment_UK_PartyLite -->
